can_update_power: true
coyote_addr_a: /avatar/parameters/EarLDis
coyote_addr_b: /avatar/parameters/EarRDis
coyote_connect_timeout: 40
coyote_max_power_a: 300
coyote_max_power_b: 300
coyote_multiplier: 7.68
coyote_pattern_a: vibrator_4
coyote_pattern_b: vibrator_4
coyote_safe_mode: true
coyote_uid: ""
max_limit: 0.8
min_limit: 0.2
min_power: 0.5
start_limit: 0.05
vrc_host: 127.0.0.1
vrc_osc_port: 9001
warn_on_stack_dump_sound: true
window_size: 0.1
